spring.application.name=paulfever


# PostgreSQL Database configuration
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.ydsxirtunyxpwvbrmjxr
spring.datasource.password=Pk13993921a@
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.port= 8080
